### ISSUE TITLE
[BUG] `install.sh` fails to verify successful installation

### ISSUE THREAD

**Issue by jahudka** [mashuptwice/hpsahba#1]
At the end of the `install.sh` script there is a check for the successful installation of the module, which basically uses `dkms status | grep -q "hpsa-dkms, 10.0"`. On my system (Ubuntu Server 22.04.1) this fails because the output of `dkms status` is slightly different:

```shell
root@example:~# dkms status
hpsa-dkms/10.0, 5.15.0-52-generic, x86_64: installed
```

Since nothing too important happens after this check I don't think it's too serious, but it still left me confused for a couple of minutes. Maybe the `grep` regexp could accommodate both formats?

**Comment by mashuptwice** [comment]
Feel free to submit a pull request.

**Comment by jahudka** [comment]
I will, over the weekend, I just wanted to report it ASAP while I still had
it all fresh on my mind, otherwise I'd forget 😂

**Comment by mashuptwice** [comment]
fixed
